/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:b11bf966-e4f8-4752-bb87-47322477361e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_o1XIUPdbV",
    "aws_user_pools_web_client_id": "2j5dr8iop54di639065uttohqk",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "bookstorev2be368aa55f214c4a8c3b091bbfd48bbc00731-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://7vnow7bqr5f47myojw3p5fc3hq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-uws4i2hce5dzhfnolsmelm245a",
    "aws_content_delivery_bucket": "bookstorev2-20211107010920-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://bookstorev2-20211107010920-hostingbucket-dev.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
